// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1vxUuyLwZNvSl74UGncCEIGpVM9aWFjU',
    appId: '1:526661486260:web:c79d381a33f6a585e8f9e1',
    messagingSenderId: '526661486260',
    projectId: 'food-ordering-app-niveus-solu',
    authDomain: 'food-ordering-app-niveus-solu.firebaseapp.com',
    storageBucket: 'food-ordering-app-niveus-solu.appspot.com',
    measurementId: 'G-8HQPXXVMVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA7xik8m_9r-HkkPStpr7MAT79sTUMIeU',
    appId: '1:526661486260:android:59c16a669f7349a7e8f9e1',
    messagingSenderId: '526661486260',
    projectId: 'food-ordering-app-niveus-solu',
    storageBucket: 'food-ordering-app-niveus-solu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqell5ZRCGVxJq4si9WgsUEn3Dh6jwfpE',
    appId: '1:526661486260:ios:1e032978e88d9adae8f9e1',
    messagingSenderId: '526661486260',
    projectId: 'food-ordering-app-niveus-solu',
    storageBucket: 'food-ordering-app-niveus-solu.appspot.com',
    iosBundleId: 'com.example.quizzAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqell5ZRCGVxJq4si9WgsUEn3Dh6jwfpE',
    appId: '1:526661486260:ios:cd4f8a20ad2f8ff3e8f9e1',
    messagingSenderId: '526661486260',
    projectId: 'food-ordering-app-niveus-solu',
    storageBucket: 'food-ordering-app-niveus-solu.appspot.com',
    iosBundleId: 'com.example.quizzAssignment.RunnerTests',
  );
}
